Pin 1279 - Notifier first implementation
pagopa/interop-be-notifier pull request #1
Opened 2022-04-27 15:19 UTC by ubaldop

2022-04-29 08:39 UTC, galales requested changes

2022-04-29 15:41 UTC, galales requested changes

2022-05-02 09:12 UTC, beetlecrunch approved these changes
It's fine for me, considering the pending changes to the audience.

2022-05-02 13:41 UTC, galales approved these changes

2022-05-02 13:42 UTC, merged